package com.lakeel.altla.ghost.alpha.google.place.web;

public enum PlaceType {

    // Indicates an unknown value that is defined on Place API, but undefined on this app.
    undefined,

    // Table 1: Types supported in place search and addition
    // https://developers.google.com/places/web-service/supported_types#table1

    accounting,
    airport,
    amusement_park,
    aquarium,
    art_gallery,
    atm,
    bakery,
    bank,
    bar,
    beauty_salon,
    bicycle_store,
    book_store,
    bowling_alley,
    bus_station,
    cafe,
    campground,
    car_dealer,
    car_rental,
    car_repair,
    car_wash,
    casino,
    cemetery,
    church,
    city_hall,
    clothing_store,
    convenience_store,
    courthouse,
    dentist,
    department_store,
    doctor,
    electrician,
    electronics_store,
    embassy,
    //    @Deprecated
    //    establishment,
    //    @Deprecated
    //    finance,
    fire_station,
    florist,
    //    @Deprecated
    //    food,
    funeral_home,
    furniture_store,
    gas_station,
    //    @Deprecated
    //    general_contractor,
    @Deprecated
    grocery_or_supermarket,
    gym,
    hair_care,
    hardware_store,
    //    @Deprecated
    //    health,
    hindu_temple,
    home_goods_store,
    hospital,
    insurance_agency,
    jewelry_store,
    laundry,
    lawyer,
    library,
    liquor_store,
    local_government_office,
    locksmith,
    lodging,
    meal_delivery,
    meal_takeaway,
    mosque,
    movie_rental,
    movie_theater,
    moving_company,
    museum,
    night_club,
    painter,
    park,
    parking,
    pet_store,
    pharmacy,
    physiotherapist,
    //    @Deprecated
    //    place_of_worship,
    plumber,
    police,
    post_office,
    real_estate_agency,
    restaurant,
    roofing_contractor,
    rv_park,
    school,
    shoe_store,
    shopping_mall,
    spa,
    stadium,
    storage,
    store,
    subway_station,
    synagogue,
    taxi_stand,
    train_station,
    transit_station,
    travel_agency,
    university,
    veterinary_care,
    zoo,

    // Table 2: Additional types returned by the Places service
    // https://developers.google.com/places/web-service/supported_types#table2

    administrative_area_level_1,
    administrative_area_level_2,
    administrative_area_level_3,
    administrative_area_level_4,
    administrative_area_level_5,
    colloquial_area,
    country,
    establishment,
    finance,
    floor,
    food,
    general_contractor,
    geocode,
    health,
    intersection,
    locality,
    natural_feature,
    neighborhood,
    place_of_worship,
    political,
    point_of_interest,
    post_box,
    postal_code,
    postal_code_prefix,
    postal_code_suffix,
    postal_town,
    premise,
    room,
    route,
    street_address,
    street_number,
    sublocality,
    sublocality_level_4,
    sublocality_level_5,
    sublocality_level_3,
    sublocality_level_2,
    sublocality_level_1,
    subpremise,

    // Address Types and Address Component Types
    // https://developers.google.com/maps/documentation/geocoding/intro#Types

    // a specific type of Japanese locality.
    ward
}
